export const states={};
export const registry={entities:[],devices:[]};
function add(id,state,name,attributes={},device='demo') {states[id]={entity_id:id,state:String(state),attributes:{friendly_name:name,...attributes}};registry.entities.push({entity_id:id,device_id:device});return id}
function metric(id,value,name,unit,dc,device){return add(id,value,name,{unit_of_measurement:unit,device_class:dc},device)}
registry.devices.push({id:'washer',name:'Washing machine',manufacturer:'Demo',model:'Washer'},{id:'water',name:'Water purifier',manufacturer:'Demo',model:'Osmosis'},{id:'robot',name:'Vacuum',manufacturer:'Demo',model:'Robot'});
add('sensor.demo_washer','washing','Lavatrice',{},'washer');metric('sensor.demo_washer_power',420,'Potenza lavatrice','W','power','washer');metric('sensor.demo_washer_energy',.38,'Energia ciclo','kWh','energy','washer');metric('sensor.demo_washer_remaining',42,'Tempo restante','min','duration','washer');metric('sensor.demo_washer_progress',64,'Avanzamento','%',null,'washer');add('select.demo_washer_program','Cotone 40°','Programma',{options:['Cotone 40°','Eco 40–60','Rapido 30′']},'washer');add('button.demo_washer_pause','unknown','Pausa',{},'washer');
add('sensor.demo_water','on','Depuratore acqua',{},'water');metric('sensor.demo_water_tds_out',18,'TDS uscita','ppm',null,'water');metric('sensor.demo_water_tds_inlet',240,'TDS ingresso','ppm',null,'water');metric('sensor.demo_water_filter_remaining',82,'Filtro residuo','%',null,'water');metric('sensor.demo_water_used',126,'Acqua erogata','L',null,'water');metric('sensor.demo_water_power',24,'Potenza depuratore','W','power','water');add('button.demo_water_flush','2026-01-01','Risciacquo',{},'water');
add('vacuum.demo_robot','cleaning','Robot pulizia',{supported_features:8192|4|8|16|32,fan_speed:'Balanced',fan_speed_list:['Quiet','Balanced','Turbo']},'robot');metric('sensor.demo_robot_battery',78,'Batteria','%','battery','robot');metric('sensor.demo_robot_area',32,'Area pulita','m²',null,'robot');add('select.demo_robot_zone','Soggiorno','Stanza',{options:['Soggiorno','Cucina','Ingresso']},'robot');add('image.demo_map','2026-01-01','Mappa',{entity_picture:'/pastel-ui/demo/map.svg'},'robot');add('button.demo_zone_kitchen','2026-01-01','Pulisci cucina',{},'robot');
add('climate.demo','cool','Climatizzatore',{supported_features:1|8|16|32,current_temperature:25.3,current_humidity:48,temperature:23,min_temp:16,max_temp:30,target_temp_step:.5,hvac_modes:['off','cool','heat','dry','fan_only'],fan_modes:['auto','low','medium','high'],fan_mode:'auto',preset_modes:['none','eco'],preset_mode:'eco',swing_modes:['off','vertical'],swing_mode:'off'});
metric('sensor.demo_temp',22.4,'Temperatura','°C','temperature');metric('sensor.demo_humidity',46,'Umidità','%','humidity');add('sensor.demo_room','22.4','Soggiorno',{temperature:22.4,humidity:46});metric('sensor.demo_target',23,'Obiettivo','°C','temperature');
add('light.demo_reading','on','Luce lettura',{brightness:153,supported_color_modes:['brightness']});add('light.demo_ceiling','off','Plafoniera',{supported_color_modes:['brightness']});
add('binary_sensor.demo_door','off','Porta ingresso',{device_class:'door'});add('binary_sensor.demo_window','on','Finestra cucina',{device_class:'window'});add('binary_sensor.demo_motion','on','Presenza soggiorno',{device_class:'occupancy'});add('binary_sensor.demo_leak','off','Sensore cucina',{device_class:'moisture'});add('binary_sensor.demo_smoke','off','Rilevatore fumo',{device_class:'smoke'});
add('lawn_mower.demo','docked','Tagliaerba',{supported_features:7});metric('sensor.demo_mower_battery',94,'Batteria','%','battery');add('switch.demo_ac','on','Climatizzatore IR');add('script.demo_on','off','Accendi clima');add('script.demo_off','off','Spegni clima');
export const examples=[
 ['appliance','Pastel Appliance',{type:'custom:pastel-appliance-card',profile:'washer',title:'Lavatrice',entity:'sensor.demo_washer',metrics:{remaining:'sensor.demo_washer_remaining',power:'sensor.demo_washer_power',cycle_energy:'sensor.demo_washer_energy',progress:'sensor.demo_washer_progress'},controls:[{entity:'select.demo_washer_program',name:'Programma'},{entity:'button.demo_washer_pause',name:'Pausa'}]}],
 ['water','Water purifier',{type:'custom:pastel-appliance-card',profile:'water_purifier',entity:'sensor.demo_water',metrics:{water_quality:'sensor.demo_water_tds_out',water_input:'sensor.demo_water_tds_inlet',filter:'sensor.demo_water_filter_remaining',power:'sensor.demo_water_power'},controls:[{entity:'button.demo_water_flush',name:'Risciacquo'}]}],
 ['robot','Pastel Robot',{type:'custom:pastel-robot-card',profile:'vacuum',entity:'vacuum.demo_robot',metrics:{battery:'sensor.demo_robot_battery',area:'sensor.demo_robot_area'},controls:[{entity:'select.demo_robot_zone',name:'Stanza'}],map_entity:'image.demo_map',zones:[{entity:'button.demo_zone_kitchen',name:'Pulisci cucina'}]}],
 ['climate','Pastel Climate',{type:'custom:pastel-climate-card',entity:'climate.demo',title:'Climatizzatore'}],
 ['lights','Pastel Lights',{type:'custom:pastel-lights-card',title:'Luci',color:'teal',entities:['light.demo_reading','light.demo_ceiling']}],
 ['button','Pastel Button',{type:'custom:pastel-button-card',title:'Scorciatoie',buttons:[{label:'Luci',icon:'mdi:lightbulb',color:'amber',action:{type:'toggle',entity_id:'light.demo_reading'}},{label:'Comfort',icon:'mdi:thermostat',color:'blue',action:{type:'more_info',entity_id:'climate.demo'}}]}],
 ['openings','Pastel Openings',{type:'custom:pastel-openings-card',title:'Aperture',color:'blue',entities:['binary_sensor.demo_door','binary_sensor.demo_window']}],
 ['doors-windows','Pastel Doors & Windows',{type:'custom:pastel-doors-windows-card',title:'Porte e finestre',color:'purple',entities:['binary_sensor.demo_door','binary_sensor.demo_window']}],
 ['motion-presence','Pastel Motion & Presence',{type:'custom:pastel-motion-presence-card',title:'Presenza',color:'teal',entities:['binary_sensor.demo_motion']}],
 ['water-leak','Pastel Water Leak',{type:'custom:pastel-water-leak-card',title:'Perdite acqua',color:'blue',entities:['binary_sensor.demo_leak']}],
 ['smoke-co','Pastel Smoke & CO',{type:'custom:pastel-smoke-co-card',title:'Fumo e CO',color:'purple',entities:['binary_sensor.demo_smoke']}],
 ['temp','Pastel Temperature',{type:'custom:pastel-temp-card',title:'Temperature',color:'blue',show_trend:false,rooms:[{name:'Soggiorno',temp_entity:'sensor.demo_temp',hum_entity:'sensor.demo_humidity'}]}],
 ['temp-humidity','Pastel Temperature & Humidity',{type:'custom:pastel-temp-humidity-card',title:'Ambienti',color:'green',rooms:[{entity:'sensor.demo_room',name:'Soggiorno'}]}],
 ['thermostat','Pastel Thermostat',{type:'custom:pastel-thermostat-card',title:'Termostato',temperature_entity:'sensor.demo_temp',humidity_entity:'sensor.demo_humidity',target_entity:'sensor.demo_target',target_service:'climate.set_temperature'}],
 ['clima','Pastel Climate · custom actions',{type:'custom:pastel-clima-card',title:'Clima IR',color:'blue',temp_entity:'sensor.demo_temp',hum_entity:'sensor.demo_humidity',power_entity:'switch.demo_ac',buttons:[{name:'Accendi',icon:'mdi:power',color:'green',action:{action:'perform-action',perform_action:'script.demo_on'}},{name:'Spegni',icon:'mdi:power',color:'red',action:{action:'perform-action',perform_action:'script.demo_off'}}]}],
 ['dishwasher','Pastel Dishwasher',{type:'custom:pastel-dishwasher-card',title:'Lavastoviglie',color:'blue',detection_mode:'power',power_entity:'sensor.demo_washer_power'}],
 ['lawn-mower','Pastel Lawn Mower',{type:'custom:pastel-lawn-mower-card',title:'Tagliaerba',mower_entity:'lawn_mower.demo',battery_entity:'sensor.demo_mower_battery',image_url:'../dist/lawn-mower.png'}],
];
const services={};for(const [domain,names] of Object.entries({vacuum:['start','pause','stop','return_to_base','set_fan_speed'],lawn_mower:['start_mowing','pause','dock','stop'],climate:['set_temperature','set_hvac_mode','set_fan_mode','set_preset_mode','set_swing_mode'],select:['select_option'],button:['press'],number:['set_value'],homeassistant:['toggle','turn_on','turn_off'],light:['turn_on'],script:['turn_on','demo_on','demo_off'],switch:['turn_on','turn_off']}))services[domain]=Object.fromEntries(names.map(n=>[n,{}]));
export const calls=[];
export const hass={states,services,connection:{},locale:{language:'it'},config:{unit_system:{temperature:'°C'}},hassUrl:path=>path,callWS:async({type})=>type==='config/entity_registry/list'?registry.entities:registry.devices,callApi:async()=>[],callService:async(domain,service,data)=>{calls.push({domain,service,data});const s=states[data.entity_id];if(s){if(service==='toggle')s.state=s.state==='on'?'off':'on';if(service==='set_temperature')Object.assign(s.attributes,data);if(service==='select_option')s.state=data.option;if(service==='set_hvac_mode')s.state=data.hvac_mode;if(service==='set_fan_mode')s.attributes.fan_mode=data.fan_mode;if(service==='turn_on')s.state='on';if(service==='turn_off')s.state='off';if(service==='turn_on'&&data.brightness_pct)s.attributes.brightness=data.brightness_pct*2.55;}window.dispatchEvent(new CustomEvent('demo-service',{detail:{domain,service,data}}))}};
