import {hass,examples} from './fixtures.js';
import '../dist/pastel-ui.js';
const icons=await fetch('./icons.json').then(r=>r.json());
customElements.define('ha-card',class extends HTMLElement{constructor(){super();this.attachShadow({mode:'open'}).innerHTML='<style>:host{display:block}</style><slot></slot>'}});
customElements.define('ha-icon',class extends HTMLElement{static observedAttributes=['icon'];constructor(){super();this.attachShadow({mode:'open'})}connectedCallback(){this.draw()}attributeChangedCallback(){this.draw()}draw(){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 24 24');svg.setAttribute('fill','currentColor');const path=document.createElementNS(svg.namespaceURI,'path');path.setAttribute('d',icons[this.getAttribute('icon')]||icons['mdi:devices']);svg.append(path);const style=document.createElement('style');style.textContent=':host{display:inline-flex;width:var(--mdc-icon-size,24px);height:var(--mdc-icon-size,24px);align-items:center;justify-content:center}svg{width:100%;height:100%}';this.shadowRoot.replaceChildren(style,svg)}});
const params=new URLSearchParams(location.search),single=params.get('card'),editor=params.get('editor'),grid=document.querySelector('.grid');const cards=[];
if(single)document.body.classList.add('single');
if(params.has('dark'))document.body.classList.add('dark');
if(editor){document.querySelector('main').classList.add('editor-view');const e=document.createElement(editor==='robot'?'pastel-robot-card-editor':'pastel-appliance-card-editor');e.setConfig({type:'custom:pastel-appliance-card',entity:'sensor.demo_washer',profile:'generic',metrics:{},controls:[]});e.hass=hass;grid.append(e);e.addEventListener('config-changed',ev=>document.querySelector('#log').textContent='Configuration saved: '+JSON.stringify(ev.detail.config));}
else for(const [id,label,config] of examples.filter(([id])=>single?id===single:params.get('view')==='new'?['appliance','water','robot','climate'].includes(id):true)){const wrap=document.createElement('section');wrap.className='item';wrap.dataset.card=id;const h=document.createElement('h2');h.textContent=label;const card=document.createElement(config.type.replace('custom:',''));card.setConfig(config);card.hass={...hass};cards.push(card);wrap.append(h,card);grid.append(wrap)}
window.addEventListener('demo-service',e=>{document.querySelector('#log').textContent='Simulated action: '+JSON.stringify(e.detail);cards.forEach(c=>c.hass={...hass})});document.addEventListener('hass-more-info',e=>document.querySelector('#log').textContent='Details: '+e.detail.entityId);document.querySelector('#theme').onclick=()=>document.body.classList.toggle('dark');
