import {html} from 'lit-element';
import {BaseCard} from './base-card.js';
import {PROFILES,METRICS,ROBOT_PROFILES} from './profiles.js';
import {getRegistry,discoverAppliances} from './discovery.js';
import {propose,profileMetrics} from './profiles.js';
export class ApplianceEditor extends BaseCard {
 static get properties(){return {...super.properties,suggestion:{},loading:{},registry:{},showAllMetrics:{}}}
 updated(){if(this.hass&&!this._discoveryStarted){this._discoveryStarted=true;this.loadDevices()}}
 chooseCandidate(key){const item=this.detected().find(d=>d.key===key);if(!item)return;this.emit({device_id:item.device_id,entity:item.entity,profile:item.profile,metrics:{},controls:[],map_entity:'',zones:[],status_entities:[]});this.suggestion={...propose(this.hass,this.registry,item),profile:item.profile}}
 detected(){return this.hass&&this.registry?discoverAppliances(this.hass,this.registry,{robot:!!this.constructor.robot}):[]}
 setConfig(c){super.setConfig(c);this.config={...c,metrics:{...(c.metrics||{})},controls:[...(c.controls||[])]}}
 emit(patch){this.config={...this.config,...patch};this.dispatchEvent(new CustomEvent('config-changed',{detail:{config:this.config},bubbles:true,composed:true}))}
 async scan(){this.loading=true;this.error='';this.suggestion=null;const identity=`${this.config.entity}|${this.config.device_id}`;try{const registry=await getRegistry(this.hass,{refresh:true});this.registry=registry;if(identity===`${this.config.entity}|${this.config.device_id}`)this.suggestion=propose(this.hass,registry,this.config)}catch{this.error='Impossibile leggere i dispositivi. Puoi comunque associare tutte le entità manualmente.'}finally{this.loading=false}}
 async loadDevices(){this.loading=true;try{this.registry=await getRegistry(this.hass)}catch{this.error='Elenco dispositivi non disponibile: seleziona un’entità.'}finally{this.loading=false}}
 options(domains){return Object.values(this.hass.states).filter(s=>!domains||domains.includes(s.entity_id.split('.')[0])).sort((a,b)=>a.entity_id.localeCompare(b.entity_id))}
 entitySelect(value,onChange,domains,label='Entità'){return html`<select aria-label=${label} .value=${value||''} @change=${e=>onChange(e.target.value)}><option value="">Nessuna</option>${this.options(domains).map(s=>html`<option value=${s.entity_id} ?selected=${value===s.entity_id}>${s.attributes.friendly_name||s.entity_id} · ${s.entity_id}</option>`)}</select>`}
 render(){if(!this.config||!this.hass)return html``;const c=this.config,s=this.suggestion,robot=this.constructor.robot;
 return html`<div class="editor" style=${this.palette(c.color)}>
  <label>Elettrodomestici rilevati${this.loading?html`<span class="hint">Ricerca automatica in corso…</span>`:html`<select aria-label="Elettrodomestici rilevati" @change=${e=>this.chooseCandidate(e.target.value)}><option value="">Scegli un dispositivo rilevato</option>${this.detected().map(d=>html`<option value=${d.key} ?selected=${d.device_id?c.device_id===d.device_id:c.entity===d.entity}>${PROFILES[d.profile][0]} · ${d.name} (${d.count} entità)</option>`)}</select>`}</label>
  <p class="hint">${this.registry&&!this.detected().length?'Nessun elettrodomestico riconosciuto. Puoi scegliere il dispositivo manualmente.':'Scegli un elettrodomestico: sensori e comandi collegati vengono proposti automaticamente. Verifica le associazioni prima di applicarle.'}</p>
  <details><summary>Scelta manuale o dispositivo non riconosciuto</summary>
  <label>Dispositivo <button ?disabled=${this.loading} @click=${()=>this.loadDevices()}>Carica elenco dispositivi</button>${this.registry?html`<select aria-label="Dispositivo" .value=${c.device_id||''} @change=${e=>{this.suggestion=null;this.emit({device_id:e.target.value,entity:'',metrics:{},controls:[],map_entity:'',zones:[],status_entities:[]})}}><option value="">Seleziona tramite entità</option>${this.registry.devices.map(d=>html`<option value=${d.id} ?selected=${c.device_id===d.id}>${d.name_by_user||d.name||d.model||d.id}</option>`)}</select>`:''}</label>
  <label>Entità principale ${this.entitySelect(c.entity,v=>{this.suggestion=null;this.emit({entity:v,device_id:'',metrics:{},controls:[],map_entity:'',zones:[],status_entities:[]})},null,'Entità principale')}</label>
  <button ?disabled=${this.loading||(!c.entity&&!c.device_id)} @click=${()=>this.scan()}>${this.loading?'Ricerca in corso…':'Cerca entità e controlli associati'}</button>
  </details>
  ${s?html`<div class="hint">${s.siblings.length} entità associate. Profilo proposto: <strong>${PROFILES[s.profile][0]}</strong>. Le associazioni verranno salvate solo quando le applichi. ${s.ambiguous.length?`Da scegliere manualmente: ${s.ambiguous.map(r=>METRICS[r][0]).join(', ')}.`:''}</div><button @click=${()=>{const {siblings,ambiguous,...mapping}=s;this.emit({...mapping,profile:robot&&!ROBOT_PROFILES.includes(s.profile)?'vacuum':s.profile});this.suggestion=null}}>Applica le associazioni proposte</button>`:''}
  <div class="pair"><label>Nome<input aria-label="Nome" .value=${c.title||''} @change=${e=>this.emit({title:e.target.value})}></label><label>Colore<select aria-label="Colore" @change=${e=>this.emit({color:e.target.value})}>${['blue','mint','peach','lavender','pink','amber'].map(v=>html`<option value=${v} ?selected=${(c.color||'blue')===v}>${v}</option>`)}</select></label></div>
  <label>Tipo dispositivo<select aria-label="Tipo dispositivo" @change=${e=>this.emit({profile:e.target.value})}>${Object.entries(PROFILES).filter(([k])=>!robot||ROBOT_PROFILES.includes(k)||k==='generic').map(([k,p])=>html`<option value=${k} ?selected=${c.profile===k}>${p[0]}</option>`)}</select></label>
  <details open><summary>Dati e consumi</summary><p class="hint">Puoi scegliere sensori esterni al dispositivo, come una presa con misurazione. L’energia del ciclo richiede un sensore dedicato.</p><label class="check"><input type="checkbox" .checked=${!!this.showAllMetrics} @change=${e=>{this.showAllMetrics=e.target.checked}}>Mostra tutti i tipi di dato</label>${Object.entries(METRICS).filter(([role])=>this.showAllMetrics||profileMetrics(c.profile).includes(role)||c.metrics?.[role]).map(([role,[label]])=>html`<label>${label}${this.entitySelect(c.metrics?.[role],v=>{const metrics={...c.metrics};if(v)metrics[role]=v;else delete metrics[role];this.emit({metrics})},['sensor'],label)}</label>`)}</details>
  <details open><summary>Controlli (${c.controls?.length||0})</summary><p class="hint">Rimuovi i comandi che non vuoi mostrare. Gli interruttori sono indicati come alimentazione, mai come avvio del programma.</p>${(c.controls||[]).map((control,i)=>html`<div class="control"><span>${control.name||control.entity||control.action}</span><button aria-label=${`Rimuovi ${control.name||control.entity}`} @click=${()=>this.emit({controls:c.controls.filter((_,j)=>j!==i)})}>Rimuovi</button></div>`)}<label>Aggiungi controllo${this.entitySelect('',v=>{if(v&&!c.controls?.some(a=>a.entity===v))this.emit({controls:[...(c.controls||[]),{entity:v,name:this.hass.states[v]?.attributes.friendly_name||v}]})},['button','input_button','switch','input_boolean','select','input_select','number','input_number','fan','humidifier','script','scene'],'Aggiungi controllo')}</label></details>
  <details><summary>Stato e manutenzione</summary>${(c.status_entities||[]).map((id,i)=>html`<div class="control"><span>${this.hass.states[id]?.attributes?.friendly_name||id}</span><button @click=${()=>this.emit({status_entities:c.status_entities.filter((_,j)=>i!==j)})}>Rimuovi</button></div>`)}${this.entitySelect('',v=>{if(v&&!c.status_entities?.includes(v))this.emit({status_entities:[...(c.status_entities||[]),v]})},['sensor','binary_sensor'],'Aggiungi stato manutenzione')}</details>
  ${robot?html`<details open><summary>Mappa e zone</summary><label>Mappa${this.entitySelect(c.map_entity,v=>this.emit({map_entity:v}),['image','camera'],'Mappa')}</label><p class="hint">La mappa è un’immagine fornita dall’integrazione. Per le zone associa un selettore tra i controlli oppure un pulsante/script qui sotto.</p>${(c.zones||[]).map((z,i)=>html`<div class="control"><span>${z.name||z.entity}</span><button @click=${()=>this.emit({zones:c.zones.filter((_,j)=>i!==j)})}>Rimuovi</button></div>`)}${this.entitySelect('',v=>{if(v)this.emit({zones:[...(c.zones||[]),{entity:v,name:this.hass.states[v]?.attributes.friendly_name||v,...(v.startsWith('script.')?{action:'script.turn_on'}:{})}]})},['button','input_button','script'],'Aggiungi zona')}</details>`:''}
  ${this.feedback()}
 </div>`;
 }
}
export class RobotEditor extends ApplianceEditor{static robot=true}
